import { colors, getThemeColor, getThemeGradient, themeColors } from './colors.js';

export const levelsStyles = {
  container: {
    minHeight: '100vh',
    background: themeColors.background.main,
  },
  backdrop: {
    color: (theme) => theme.palette.mode === 'dark' ? colors.special.white : colors.text.dark,
    zIndex: (theme) => theme.zIndex.drawer + 1,
    backgroundColor: (theme) => theme.palette.mode === 'dark' ? 'rgba(15, 15, 15, 0.85)' : 'rgba(255,255,255,0.85)',
    backdropFilter: 'blur(8px)',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 1.5,
    p: 3,
    borderRadius: 2,
    backgroundColor: (theme) => theme.palette.mode === 'dark' ? 'rgba(25, 25, 25, 0.95)' : 'rgba(255,255,255,0.98)',
    color: (theme) => theme.palette.mode === 'dark' ? colors.special.white : colors.text.dark,
    backdropFilter: 'blur(10px)',
    border: themeColors.card.border,
  },
  pageContainer: {
    py: 3,
  },
  pageTitle: {
    mb: 3,
    fontWeight: 700,
    fontSize: '2rem',
    color: themeColors.text.primary,
    textAlign: 'center',
  },
  tabsContainer: {
    borderBottom: 'none',
    mb: 4,
    px: 2,
    py: 2,
    display: 'flex',
    justifyContent: 'center',
    '& .MuiTabs-root': {
      backgroundColor: themeColors.overlay.card,
      borderRadius: 4,
      outline: 'none',
      p: 1,
      pt: 1.5,
      pb: 1,
      minHeight: 56,
      overflow: 'visible',
    },
    '& .MuiTab-root': {
      fontWeight: 600,
      fontSize: '0.95rem',
      textTransform: 'none',
      minHeight: 44,
      px: 4,
      py: 1.5,
      mx: 0.5,
      borderRadius: 3,
      color: themeColors.text.secondary,
      transition: 'background-color 0.3s ease',
      position: 'relative',
      overflow: 'hidden',
      outline: 'none',
      '&:focus': {
        outline: 'none',
      },
      '&:focus-visible': {
        outline: 'none',
        boxShadow: getThemeColor(colors.border.light.focus, colors.border.dark.focus),
      },
      '&:focus-within': {
        outline: 'none',
      },
      '&:hover': {
        backgroundColor: themeColors.ui.hover,
        color: themeColors.text.primary,
      },
      '&.Mui-selected': {
        background: getThemeColor(colors.ui.light.buttonPrimary, colors.ui.dark.buttonPrimary),
        color: 'white',
        fontWeight: 700,
        boxShadow: getThemeColor(
          `0 0 0 1px ${colors.border.light.focus}, 0 2px 6px ${colors.shadow.light.primary}`,
          `0 0 0 1px ${colors.border.dark.focus}, 0 2px 6px ${colors.shadow.dark.primary}`
        ),
        '&::before': {
          content: '""',
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: themeColors.ui.selected,
          borderRadius: 3,
          pointerEvents: 'none',
        },
      },
    },
    '& .MuiTabs-indicator': {
      display: 'none',
    },
    '& .MuiTabs-flexContainer': {
      gap: 1,
    },
  },
  gridContainer: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
      lg: 'repeat(4, 1fr)',
      xl: 'repeat(5, 1fr)'
    },
    gap: 2,
    alignItems: 'stretch',
    px: 1,
    maxWidth: '1400px',
    margin: '0 auto',
  },
  levelCard: {
    height: '100%',
    width: '100%',
    minWidth: {
      xs: '280px',
      sm: '300px',
      md: '320px'
    },
    maxWidth: {
      xs: '100%',
      sm: '350px',
      md: '330px'
    },
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 3,
    transition: 'all 0.3s ease',
    background: themeColors.card.background,
    backdropFilter: 'blur(20px)',
    border: themeColors.card.border,
    boxShadow: themeColors.card.shadow,
    overflow: 'hidden',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '3px',
      background: getThemeColor(colors.ui.light.buttonPrimary, colors.ui.dark.buttonPrimary),
      opacity: 0,
      transition: 'opacity 0.3s ease',
    },
  },
  lockedCard: {
    opacity: 0.75,
    filter: 'grayscale(0.2)',
    '&:hover': {
      background: themeColors.ui.hover,
      cursor: 'not-allowed',
    },
  },
  activeCard: {
    '&:hover': {
      background: themeColors.ui.hover,
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: getThemeColor(
        '0 4px 12px rgba(0, 0, 0, 0.15)',
        '0 4px 12px rgba(0, 0, 0, 0.6)'
      ),
      '&::before': {
        opacity: 1,
      },
    },
  },
  cardContent: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    p: 2,
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 1.5,
  },
  cardTitle: {
    fontWeight: 700,
    fontSize: '1.1rem',
    color: themeColors.text.primary,
    letterSpacing: '-0.02em',
    lineHeight: 1.2,
  },
  cardDescription: {
    color: themeColors.text.secondary,
    mb: 2,
    flexGrow: 1,
    fontSize: '0.85rem',
    lineHeight: 1.4,
    fontWeight: 400,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  topicsContainer: {
    mb: 2,
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.5,
  },
  topicChip: {
    fontSize: '0.7rem',
    fontWeight: 500,
    height: 22,
    background: getThemeColor(colors.ui.light.topicAccent, colors.ui.dark.topicAccent),
    color: 'white',
    border: 'none',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.2s ease',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(80px, 1fr))',
    gap: 1,
    mb: 2,
  },
  metricCard: {
    p: 1.5,
    borderRadius: 2,
    background: getThemeColor(colors.ui.light.cardHover, colors.ui.dark.cardHover),
    border: getThemeColor(colors.border.light.secondary, colors.border.dark.secondary),
    textAlign: 'center',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      background: themeColors.ui.hover,
    },
  },
  metricIcon: {
    fontSize: '1rem',
    mb: 0.3,
    display: 'block',
    color: getThemeColor(colors.ui.light.topicPrimary, colors.ui.dark.topicPrimary),
  },
  metricValue: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: themeColors.text.primary,
    lineHeight: 1.1,
    mb: 0.3,
  },
  metricLabel: {
    fontSize: '0.65rem',
    color: themeColors.text.secondary,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  progressContainer: {
    mb: 3,
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: getThemeColor(colors.border.light.secondary, colors.border.dark.secondary),
    '& .MuiLinearProgress-bar': {
      background: getThemeColor(colors.ui.light.buttonPrimary, colors.ui.dark.buttonPrimary),
      borderRadius: 3,
    },
  },
  progressLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 1,
  },
  progressText: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: themeColors.text.primary,
  },
  progressPercentage: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: themeColors.text.primary,
  },
  buttonsContainer: {
    display: 'flex',
    gap: 1,
    p: 1.5,
    pt: 0,
  },
  startButton: {
    sx: {
      background: getThemeColor(colors.ui.light.buttonPrimary, colors.ui.dark.buttonPrimary),
      color: 'white',
      fontWeight: 600,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 3,
      py: 1,
      fontSize: '0.85rem',
      boxShadow: getThemeColor(colors.shadow.light.primary, colors.shadow.dark.primary),
      '&:hover': {
        background: getThemeColor(colors.ui.light.buttonSuccess, colors.ui.dark.buttonSuccess),
        transform: 'translateY(-1px)',
        boxShadow: getThemeColor(colors.shadow.light.medium, colors.shadow.dark.medium),
      },
      transition: 'all 0.3s ease',
    },
  },
  lockedButton: {
    sx: {
      color: themeColors.text.disabled,
      backgroundColor: themeColors.overlay.low,
      fontWeight: 500,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 3,
      py: 1,
      fontSize: '0.85rem',
      cursor: 'not-allowed',
      border: themeColors.card.border,
    },
  },
  lockIcon: {
    color: themeColors.text.disabled,
    backgroundColor: themeColors.overlay.low,
    borderRadius: '50%',
    p: 0.3,
    fontSize: '1rem',
    border: themeColors.card.border,
  },
}; 