import { colors, getThemeColor, getThemeGradient, themeColors } from './colors.js';

export const levelsStyles = {
  container: {
    minHeight: '100vh',
    background: themeColors.background.main,
  },
  backdrop: {
    color: colors.special.white,
    zIndex: (theme) => theme.zIndex.drawer + 1,
    backgroundColor: colors.special.backdrop,
    backdropFilter: 'blur(8px)',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 1.5,
    p: 3,
    borderRadius: 2,
    backgroundColor: themeColors.overlay.card,
    backdropFilter: 'blur(10px)',
    border: themeColors.card.border,
  },
  pageContainer: {
    py: 3,
  },
  pageTitle: {
    mb: 3,
    fontWeight: 700,
    fontSize: '2rem',
    background: colors.gradients.primary,
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textAlign: 'center',
  },
  tabsContainer: {
    borderBottom: 'none',
    mb: 4,
    px: 2,
    py: 2,
    display: 'flex',
    justifyContent: 'center',
    '& .MuiTabs-root': {
      backgroundColor: themeColors.overlay.card,
      borderRadius: 4,
      outline: 'none',
      p: 1,
      pt: 1.5,
      pb: 1,
      minHeight: 56,
      overflow: 'visible',
    },
    '& .MuiTab-root': {
      fontWeight: 600,
      fontSize: '0.95rem',
      textTransform: 'none',
      minHeight: 44,
      px: 4,
      py: 1.5,
      mx: 0.5,
      borderRadius: 3,
      color: themeColors.text.secondary,
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      position: 'relative',
      overflow: 'hidden',
      outline: 'none',
      '&:focus': {
        outline: 'none',
      },
      '&:focus-visible': {
        outline: 'none',
        boxShadow: getThemeColor(colors.border.light.focus, colors.border.dark.focus),
      },
      '&:focus-within': {
        outline: 'none',
      },
      '&:hover': {
        backgroundColor: getThemeColor(colors.overlay.light.medium, colors.overlay.dark.medium),
        color: themeColors.text.primary,
        transform: 'scale(1.02)',
      },
      '&.Mui-selected': {
        background: colors.gradients.primary,
        color: colors.special.white,
        fontWeight: 700,
        boxShadow: getThemeColor(
          `0 0 0 1px ${colors.border.light.focus}, 0 2px 6px ${colors.shadow.light.primary}`,
          `0 0 0 1px ${colors.border.dark.focus}, 0 2px 6px ${colors.shadow.dark.primary}`
        ),
        transform: 'scale(1.03)',
        '&::before': {
          content: '""',
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: colors.gradients.overlayLight,
          borderRadius: 3,
          pointerEvents: 'none',
        },
      },
    },
    '& .MuiTabs-indicator': {
      display: 'none',
    },
    '& .MuiTabs-flexContainer': {
      gap: 1,
    },
  },
  gridContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: 2,
    alignItems: 'stretch',
    px: 1,
    maxWidth: '1400px',
    margin: '0 auto',
  },
  levelCard: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 3,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    background: themeColors.card.background,
    backdropFilter: 'blur(20px)',
    border: themeColors.card.border,
    boxShadow: themeColors.card.shadow,
    overflow: 'hidden',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '3px',
      background: colors.gradients.rainbow,
      opacity: 0,
      transition: 'opacity 0.3s ease',
    },
  },
  lockedCard: {
    opacity: 0.75,
    filter: 'grayscale(0.2)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: getThemeColor(colors.shadow.light.medium, colors.shadow.dark.medium),
      cursor: 'not-allowed',
    },
  },
  activeCard: {
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: getThemeColor(colors.shadow.light.primaryHigh, colors.shadow.dark.primaryHigh),
      cursor: 'pointer',
      '&::before': {
        opacity: 1,
      },
    },
  },
  cardContent: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    p: 2,
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 1.5,
  },
  cardTitle: {
    fontWeight: 700,
    fontSize: '1.1rem',
    background: colors.gradients.primary,
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.02em',
    lineHeight: 1.2,
  },
  cardDescription: {
    color: 'text.secondary',
    mb: 2,
    flexGrow: 1,
    fontSize: '0.85rem',
    lineHeight: 1.4,
    fontWeight: 400,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  topicsContainer: {
    mb: 2,
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.5,
  },
  topicChip: {
    fontSize: '0.7rem',
    fontWeight: 500,
    height: 22,
    background: getThemeGradient(colors.gradients.chipLight, colors.gradients.chipDark),
    color: colors.primary.main,
    border: getThemeColor(colors.border.light.accent, colors.border.dark.accent),
    '&:hover': {
      background: getThemeGradient(colors.gradients.chipLightHover, colors.gradients.chipDarkHover),
      transform: 'translateY(-1px)',
    },
    transition: 'all 0.2s ease',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(80px, 1fr))',
    gap: 1,
    mb: 2,
  },
  metricCard: {
    p: 1.5,
    borderRadius: 2,
    background: getThemeGradient(colors.gradients.cardLightGlass, colors.gradients.cardDarkGlass),
    border: getThemeColor(colors.border.light.secondary, colors.border.dark.secondary),
    textAlign: 'center',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: getThemeColor(colors.shadow.light.primaryMedium, colors.shadow.dark.primaryMedium),
    },
  },
  metricIcon: {
    fontSize: '1rem',
    mb: 0.3,
    display: 'block',
  },
  metricValue: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: colors.primary.main,
    lineHeight: 1.1,
    mb: 0.3,
  },
  metricLabel: {
    fontSize: '0.65rem',
    color: 'text.secondary',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  progressContainer: {
    mb: 3,
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border.light.secondary,
    '& .MuiLinearProgress-bar': {
      background: colors.gradients.primary,
      borderRadius: 3,
    },
  },
  progressLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 1,
  },
  progressText: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: colors.primary.main,
  },
  progressPercentage: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: colors.primary.main,
  },
  activeSessionContainer: {
    mt: 1.5,
    p: 2,
    background: getThemeGradient(colors.gradients.sessionLight, colors.gradients.sessionDark),
    borderRadius: 2,
    border: getThemeColor(colors.warning.accent, colors.warning.lighter),
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '2px',
      background: colors.gradients.sessionWarning,
    },
  },
  activeSessionTitle: {
    color: colors.warning.orange,
    fontSize: '0.8rem',
    fontWeight: 700,
    mb: 1,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  activeSessionStats: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 1,
  },
  activeSessionStat: {
    textAlign: 'center',
    p: 1,
    background: getThemeColor(colors.overlay.light.card, colors.overlay.dark.low),
    borderRadius: 1,
    border: getThemeColor(colors.warning.accent, colors.warning.lighter),
  },
  activeSessionStatValue: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: colors.warning.dark,
    mb: 0.3,
  },
  activeSessionStatLabel: {
    fontSize: '0.65rem',
    color: colors.warning.orange,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  buttonsContainer: {
    display: 'flex',
    gap: 1,
    p: 1.5,
    pt: 0,
  },
  reconnectButton: {
    size: 'small',
    color: 'warning',
    variant: 'contained',
    sx: {
      background: colors.gradients.warning,
      color: colors.special.white,
      fontWeight: 600,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 2,
      py: 0.5,
      fontSize: '0.8rem',
      boxShadow: colors.shadow.light.warning,
      '&:hover': {
        background: colors.gradients.warningAlt,
        transform: 'translateY(-1px)',
        boxShadow: colors.shadow.light.warningHigh,
      },
      transition: 'all 0.3s ease',
    },
  },
  startFreshButton: {
    size: 'small',
    color: 'error',
    variant: 'outlined',
    sx: {
      borderColor: colors.error.main,
      color: colors.error.main,
      fontWeight: 600,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 2,
      py: 0.5,
      fontSize: '0.8rem',
      borderWidth: 1.5,
      '&:hover': {
        backgroundColor: colors.error.main,
        color: colors.special.white,
        transform: 'translateY(-1px)',
        boxShadow: colors.shadow.light.error,
      },
      transition: 'all 0.3s ease',
    },
  },
  startButton: {
    color: 'primary',
    sx: {
      background: colors.gradients.primary,
      color: colors.special.white,
      fontWeight: 600,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 3,
      py: 1,
      fontSize: '0.85rem',
      boxShadow: colors.shadow.light.primary,
      '&:hover': {
        background: colors.gradients.primaryAlt,
        transform: 'translateY(-1px)',
        boxShadow: colors.shadow.light.primaryHigh,
      },
      transition: 'all 0.3s ease',
    },
  },
  lockedButton: {
    sx: {
      color: 'text.disabled',
      backgroundColor: themeColors.overlay.low,
      fontWeight: 500,
      textTransform: 'none',
      borderRadius: 1.5,
      px: 3,
      py: 1,
      fontSize: '0.85rem',
      cursor: 'not-allowed',
      border: themeColors.card.border,
    },
  },
  lockIcon: {
    color: 'text.disabled',
    backgroundColor: themeColors.overlay.low,
    borderRadius: '50%',
    p: 0.3,
    fontSize: '1rem',
    border: themeColors.card.border,
  },
}; 